import { UnidadTemperatura } from "../enums/unidad-temperatura.enum";
import { PrediccionDto } from "../interfaces/prediccion.dto";

export const prediccionPlaceholder: PrediccionDto = {
  "temperaturaMedia": 27,
  "unidadTemperatura": UnidadTemperatura.celsius,
  "probabilidadPrecipitacion": [
    {
      "autoGeneratedId": 0,
      "probabilidad": 0,
      "periodo": "00-06"
    },
    {
      "autoGeneratedId": 1,
      "probabilidad": 0,
      "periodo": "06-12"
    },
    {
      "autoGeneratedId": 2,
      "probabilidad": 0,
      "periodo": "12-18"
    },
    {
      "autoGeneratedId": 3,
      "probabilidad": 0,
      "periodo": "18-24"
    }
  ]
};

export const municipioPlaceholder = 'Sueca';