import { UnidadTemperatura } from "../enums/unidad-temperatura.enum";

export interface PrediccionDto {
  temperaturaMedia: number;
  unidadTemperatura?: UnidadTemperatura;
  probabilidadPrecipitacion: ProbabilidadPrecipitacion[];
}

export interface ProbabilidadPrecipitacion {
  autoGeneratedId?: number;
  probabilidad: number;
  periodo: string;
}