import { UnidadTemperatura } from "../enums/unidad-temperatura.enum";

export interface PrediccionDto {
  temperaturaMedia: number;
  unidadTemperatura: UnidadTemperatura;
  probabilidadPrecipitacion: ProbabilidadPrecipitacionDto[];
}

export interface ProbabilidadPrecipitacionDto {
  autoGeneratedId: number;
  probabilidad: number;
  periodo: string;
}